# Generated by Django 4.2.30 on 2026-05-16 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('style', models.CharField(choices=[('murattal', 'Murattal'), ('mujawwad', 'Mujawwad'), ('muallim', 'Muallim')], default='murattal', max_length=15)),
                ('audio_base_url', models.URLField(help_text='CDN base URL pattern, e.g. https://cdn.islamic.network/quran/audio/128/en.alafasy')),
                ('image_url', models.URLField(blank=True)),
                ('bitrate', models.PositiveSmallIntegerField(default=128)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='UserPlaybackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('single', 'Single Verse'), ('surah', 'Full Surah'), ('range', 'Verse Range'), ('loop', 'Loop')], default='single', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reciter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.reciter')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.surah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_history', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quran.verse')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audio_userp_user_id_0e02f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AudioEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('reciter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='audio.reciter')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_editions', to='quran.surah')),
            ],
            options={
                'unique_together': {('reciter', 'surah')},
            },
        ),
    ]
