# Generated by Django 4.2.30 on 2026-05-16 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HifzSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('blind', 'Blind Mode'), ('hint', 'Hint Mode')], default='hint', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('verses_attempted', models.PositiveSmallIntegerField(default=0)),
                ('verses_correct', models.PositiveSmallIntegerField(default=0)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.surah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HifzProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('memorized', 'Memorized'), ('weak', 'Weak')], db_index=True, default='new', max_length=12)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('repetitions', models.PositiveSmallIntegerField(default=0)),
                ('next_review', models.DateField(default=django.utils.timezone.now)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_errors', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_progress', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_progress', to='quran.verse')),
            ],
            options={
                'ordering': ['next_review'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('RED', 'Major Mistake'), ('YELLOW', 'Minor Mistake')], db_index=True, max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='hifz.hifzsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_errors', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='quran.verse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hifzsession',
            index=models.Index(fields=['user', '-started_at'], name='hifz_hifzse_user_id_5a91a2_idx'),
        ),
        migrations.AddIndex(
            model_name='hifzprogress',
            index=models.Index(fields=['user', 'status'], name='hifz_hifzpr_user_id_c19408_idx'),
        ),
        migrations.AddIndex(
            model_name='hifzprogress',
            index=models.Index(fields=['user', 'next_review'], name='hifz_hifzpr_user_id_0fbf69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hifzprogress',
            unique_together={('user', 'verse')},
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['user', 'verse'], name='hifz_errorl_user_id_ba7f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['user', 'error_type'], name='hifz_errorl_user_id_c06f72_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['user', '-created_at'], name='hifz_errorl_user_id_0a1b43_idx'),
        ),
    ]
