# Generated by Django 4.2.30 on 2026-05-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('name_arabic', models.CharField(max_length=100)),
                ('name_transliteration', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_tr', models.CharField(blank=True, max_length=100)),
                ('revelation_type', models.CharField(choices=[('meccan', 'Meccan'), ('medinan', 'Medinan')], max_length=10)),
                ('total_verses', models.PositiveSmallIntegerField()),
                ('page_start', models.PositiveSmallIntegerField(default=1)),
                ('page_end', models.PositiveSmallIntegerField(default=1)),
                ('revelation_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Surah',
                'verbose_name_plural': 'Surahs',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('text_arabic', models.TextField()),
                ('text_transliteration', models.TextField(blank=True)),
                ('page_number', models.PositiveSmallIntegerField(db_index=True)),
                ('juz_number', models.PositiveSmallIntegerField(db_index=True)),
                ('hizb_quarter', models.PositiveSmallIntegerField(default=1)),
                ('is_sajda', models.BooleanField(default=False)),
                ('global_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Verse',
                'verbose_name_plural': 'Verses',
                'ordering': ['surah__number', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uz_latin', "O'zbekcha"), ('uz_cyrillic', 'Ўзбекча')], db_index=True, max_length=12)),
                ('text', models.TextField()),
                ('source', models.CharField(blank=True, choices=[('sahih_international', 'Sahih International'), ('kuliyev', 'Elmir Kuliyev'), ('diyanet', 'Diyanet İşleri'), ('uz_tashkent', 'Toshkent Mushafi')], max_length=30)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quran.verse')),
            ],
        ),
        migrations.CreateModel(
            name='Tafsir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uz_latin', "O'zbekcha"), ('uz_cyrillic', 'Ўзбекча')], db_index=True, max_length=12)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tafsirs', to='quran.verse')),
            ],
        ),
        migrations.CreateModel(
            name='PageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField(unique=True)),
                ('verse_start', models.PositiveSmallIntegerField()),
                ('juz_number', models.PositiveSmallIntegerField()),
                ('surah_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_starts', to='quran.surah')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['page_number'], name='quran_verse_page_nu_87b23d_idx'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['juz_number'], name='quran_verse_juz_num_8d1628_idx'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['surah', 'number'], name='quran_verse_surah_i_291d60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('surah', 'number')},
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['verse', 'language'], name='quran_trans_verse_i_dd0e86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('verse', 'language')},
        ),
        migrations.AddIndex(
            model_name='tafsir',
            index=models.Index(fields=['verse', 'language'], name='quran_tafsi_verse_i_274323_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tafsir',
            unique_together={('verse', 'language')},
        ),
    ]
